language: python
matrix:
  include:
    - python: 3.7
      env: TOX_ENV=py37-lint_docstrings
  allow_failures:
    - env: TOX_ENV=py37-lint_docstrings

install:
  - pip install tox

script: tox -e $TOX_ENV
